runtime: python39

env_variables:
  SECRET_KEY: <YOUR_SECRET_KEY>
  MYSQL_CONNECTION: <YOUR_MYSQL_CONNECTION>
  MYSQL_USERNAME: <YOUR_MYSQL_USERNAME>
  MYSQL_PASSWORD: <YOUR_MYSQL_PASSWORD>
  MYSQL_DATABASE: <YOUR_MYSQL_DATABASE>
  DPY_COC: <DPY_COC_URL>
  DPY_GUIDE: <DPY_GUIDE_URL>
  C4T_DPY_D1: <DPY_D1_URL>
  C4T_DPY_D2: <DPY_D2_URL>
  C4T_DPY_D3: <DPY_D3_URL>
  C4T_DPY_D4: <DPY_D4_URL>
  C4T_DPY_D5: <DPY_D5_URL>
  C4T_DPY_D6: <DPY_D6_URL>
  C4T_DPY_D7: <DPY_D7_URL>
  C4T_DPY_D8: <DPY_D8_URL>
  C4T_DPY_D9: <DPY_D9_URL>
  C4W_DPY_D1: <C4W_DPY_D1_URL>
  C4W_DPY_D2: <C4W_DPY_D2_URL>
  C4W_DPY_D3: <C4W_DPY_D3_URL>
  C4W_DPY_D4: <C4W_DPY_D4_URL>
  C4W_DPY_D5: <C4W_DPY_D5_URL>
