runtime: python39

env_variables:
  SECRET_KEY: <YOUR_SECRET_KEY>
  MYSQL_CONNECTION: <YOUR_MYSQL_CONNECTION>
  MYSQL_USERNAME: <YOUR_MYSQL_USERNAME>
  MYSQL_PASSWORD: <YOUR_MYSQL_PASSWORD>
  MYSQL_DATABASE: <YOUR_MYSQL_DATABASE>
